### ISSUE TITLE
Updated terraform provider removes `security_group_rules` in `gcore_k8sv2`

### ISSUE THREAD

**Issue by zadjadr** [G-Core/terraform-provider-gcore#154]
After an update to the latest gcore terraform version, I see a change in `gcore_k8sv2` that is unexpected. All security group rules will be removed (seems to be a new entity in `gcore_k8sv2`).

Should we remove the security group rules, because they will be managed elsewhere or should be add the security group rules to our terraform file / are we now responsible for managing security group rules related to Kubernetes?

Example: 

```
      - security_group_rules {
          - created_at       = "2024-03-15 12:12:20 +0000 +0000" -> null
          - direction        = "egress" -> null
          - ethertype        = "IPv4" -> null
          - id               = "XXX" -> null
          - port_range_max   = 24 -> null
          - port_range_min   = 1 -> null
          - protocol         = "tcp" -> null
          - updated_at       = "2024-03-15 12:12:20 +0000 +0000" -> null
            # (2 unchanged attributes hidden)
        }
        .......
        .......
      - security_group_rules {
          - created_at       = "2024-09-03 08:16:25 +0000 +0000" -> null
          - direction        = "ingress" -> null
          - ethertype        = "IPv6" -> null
          - id               = "YYY" -> null
          - port_range_max   = 10249 -> null
          - port_range_min   = 10249 -> null
          - protocol         = "tcp" -> null
          - updated_at       = "2024-09-03 08:16:25 +0000 +0000" -> null
            # (2 unchanged attributes hidden)
        }
```

**Comment by alexk53** [comment]
We found the reason, could you provide cluster name and the region?
We need to add some system tags to security group rules and everything should be fine.

**Comment by zadjadr** [comment]
> We found the reason, could you provide cluster name and the region? We need to add some system tags to security group rules and everything should be fine.

Cool, thanks! 

Region: Frankfurt
Cluster: mgmt

**Comment by zadjadr** [comment]
We have the same issue with another cluster 

Region: Frankfurt
Cluster: staging

If you need further details like ID etc. Let me know and I can open a support ticket

**Comment by gbernady** [comment]
We have finally resolved the issue on our end, and we apologize for the delay in addressing it.

When running `terraform apply`, you may notice that one or two rules still appear as being removed, depending on the cluster. These rules are not required from our side, but we could not completely rule out the possibility that they might be necessary for your setup.

If they are not needed, you can safely ignore these messages and they will get cleaned up by terraform. Otherwise, you will need move the ones you need to the terraform file.

**Comment by zadjadr** [comment]
@gbernady thanks! I applied the change and the rules were removed but not added back. For now, the cluster looks fine - if anything breaks, I'll just open a ticket. This issue can be closed with this. Thanks :+1:
