### ISSUE TITLE
Use an environment variable for `permanent_api_token`

### ISSUE THREAD

**Issue by andreas-kokkalis** [G-Core/terraform-provider-gcore#155]
Is it possible to set the `permanent_api_token` via an environment variable such as `GCORE_PERMANENT_API_TOKEN`?

How do people work with gcore provider within git repositories and CI/CD without exposing sensitive information in source code?

**Comment by daragok** [comment]
hi @andreas-kokkalis 
thank you for the feedback! 

we'll add it to the docs section
