### ISSUE TITLE
[cdn] gcore_cdn_rule import example

### ISSUE THREAD

**Issue by bazilek** [G-Core/terraform-provider-gcore#16]
Please provide import for gcore_cdn_rule and other gcore_cdn_* resources, now addressing part is unclear

**Comment by CostaGCore** [comment]
We've added this to our internal work plan: CDN-6169

**Comment by freenoth** [comment]
Now CDN rules can be imported using `<resource_id>:<rule_id>` as ADDR ID param for `terraform import gcore_cdn_rule.<name> ADDR ID` command

**Comment by freenoth** [comment]
example `terraform import gcore_cdn_rule.rule2 540339:1501744`
