### ISSUE TITLE
changes in gcore_cdn_resource options are not detected when not specified

### ISSUE THREAD

**Issue by rasschaert** [G-Core/terraform-provider-gcore#39]
I've set up a CDN resource with the Terraform provider with a resource definition that looked something like this.

```
resource "gcore_cdn_resource" "foo" {
  cname           = "foo.example.org"
  origin_group    = gcore_cdn_origingroup.foo.id
  origin_protocol = "HTTPS"
  ssl_enabled     = true
  ssl_data        = gcore_cdn_sslcert.letsencrypt_foo.id
  options {
    host_header { value = "www-origin.example.org" }
    stale {
      enabled = true
      value = [
        "error",
        "updating",
        "timeout",
      ]
    }
    redirect_http_to_https { value = true }
    gzip_on { value = true }
    cors { value = ["*"] }
  }
}
```

Then I made manual changes in the web interface. I enabled CDN caching and Browser caching. When I went back to Terraform I expected to see those manual changes, but `terraform apply` responded with `No changes. Your infrastructure still matches the configuration.`.

It appears that since I didn't specify values `edge_cache_settings` and `browser_cache_settings`, it didn't notice the changes that were made.

I could however see the changed values when quering the Terraform cache.

<img width="1141" alt="image" src="https://github.com/G-Core/terraform-provider-gcore/assets/1173314/7a4846ab-24db-4959-b14e-7983b601688d">

When these two options are explicitly specified, the changes are being correctly detected by Terraform.

<img width="709" alt="image" src="https://github.com/G-Core/terraform-provider-gcore/assets/1173314/89d7ed18-541d-4ef1-8a4e-f0916d71b330">

So far I've only had this issue with  the options`edge_cache_settings` and `browser_cache_settings`. Changes that I made manually to the `tls_versions` option _are_ correctly being noticed, even when the option is absent from the resource configuration.

```
        # (8 unchanged attributes hidden)

      ~ options {
          - tls_versions {
              - enabled = true -> null
              - value   = [
                  - "TLSv1.2",
                  - "TLSv1.3",
                ] -> null
            }

            # (7 unchanged blocks hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by CostaGCore** [comment]
@rasschaert , thanks for reporting this issue. We've added it to our backlog and will work on it in the coming week or two. [CDN-7398]

**Comment by andrei-lukyanchyk** [comment]
Hi @rasschaert,

Actually it is expected behaviour for these options. We have a set of computed options (listed below) for which default values applied on the backend side if there no specified value in the Terraform's config. It is a reason why the Terraform doesn't detect changes for them. So, if you need to specify your own value for these options, please add them to your Terraform config.

- allowed_http_methods
- browser_cache_settings
- cache_http_headers
- edge_cache_settings
- sni
- stale
