### ISSUE TITLE
Can not use redirect_http_to_https option

### ISSUE THREAD

**Issue by CostaGCore** [G-Core/terraform-provider-gcore#6]
One can not use redirect_http_to_https option even when tls is enabled

│ Error: request: {
│ "options": {
│ "redirect_http_to_https": {
│ "enabled": [
│ "You cannot enable redirect HTTP to HTTPS when HTTPS is disabled. Please enable HTTPS and add SSL certificate first"
│ ]
│ }
│ }
│ }

configuration snippet

  ssl_enabled = true
  ssl_data = ssl_cert_id
  options {
    tls_versions {
      enabled = true
      value   = [
        "TLSv1.2",
        "TLSv1.3",
      ]
    }
    redirect_http_to_https {
      enabled = true
      value = true
    }

This is a copy of: https://github.com/G-Core/terraform-provider-gcorelabs/issues/106

**Comment by andrei-lukyanchyk** [comment]
@bazilek,
I can't reproduce this issue, it works well for me. Could you check and confirm that you still facing this issue?
