### ISSUE TITLE
Unable to destroy gcore_k8sv2 cluster

### ISSUE THREAD

**Issue by vkolesnikov-oneup** [G-Core/terraform-provider-gcore#64]
Terraform
1.5.7
Gcore
Installed g-core/gcore v0.3.100 

Config:
'
terraform {
  backend "gcs" {
  }
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    gcore = {
      source  = "G-Core/gcore"
      version = ">= 0.3.100"
    }
    google = {
      source  = "hashicorp/google"
      version = "~> 5.10"
    }
  }
}

provider gcore {
permanent_api_token = var.permanent_api_token
}

provider "google" {

}
resource "gcore_k8sv2" "gss" {
  project_id    = local.project_id
  region_id     = var.region 
  name          = "gss-${var.region_name}-${var.env}"
  fixed_network = gcore_network.network.id
  fixed_subnet  = gcore_subnet.subnet.id
  keypair       = gcore_keypair.kp.id
  version       = "v1.28.4"
  pool {
    name             = "pool-l1"
    flavor_id        = var.l1_instance_types
    min_node_count   = lookup(var.asg_size["default"],"l1")["min_size"]
    max_node_count   = lookup(var.asg_size["default"],"l1")["max_size"]
    boot_volume_size = 50
    boot_volume_type = "standard"
    is_public_ipv4   = true
    auto_healing_enabled = true
  }
    pool {
    name             = "public"
    flavor_id        = var.public_instance_types
    min_node_count   = lookup(var.asg_size["default"],"public")["min_size"]
    max_node_count   = lookup(var.asg_size["default"],"public")["max_size"]
    boot_volume_size = 50
    boot_volume_type = "standard"
    is_public_ipv4   = true
    auto_healing_enabled = true
  }
}
'

Error:
│ Error: task is in error state: ERROR. Error: object DictWithMeta can't be used in 'await' expression
│

**Comment by gbernady** [comment]
Hi, sorry for the late reply.

The problem mentioned here was fixed in February, so I'm closing this issue.
