### ISSUE TITLE
Recreating a manually deleted cluster

### ISSUE THREAD

**Issue by zadjadr** [G-Core/terraform-provider-gcore#86]
If a cluster previously created with terraform is deleted manually in the UI, we expect that terraform does not fail and just creates the cluster if it is not found.

The terraform provider should create a non-existent cluster without forcing the user to fiddle with the terraform state manually (currently we would need remove the cluster from the state and reapply)

```
Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Error: Cluster staging is not found
│
│   with gcore_k8sv2.mi-staging,
│   on k8s-cluster.tf line 2, in resource "gcore_k8sv2" "mi-staging":
│    2: resource "gcore_k8sv2" "mi-staging" {
│
╵
```

**Comment by alexk53** [comment]
Thank you! We will take to work as soon as possible.

**Comment by alexk53** [comment]
In version v0.5.1 we remove cluster from the state if it doesn't exist in the infrastructure.

**Comment by zadjadr** [comment]
Nice, thanks!
